---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: tomas@mihalicka.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: monadial-account-key
    solvers:
      - http01:
          ingress:
            class: traefik-cert-manager